##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-crypto-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "labels.pvc" . | nindent 2 }}  
spec:
  storageClassName: storage-{{ .Release.Name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-tools-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "labels.pvc" . | nindent 2 }} 
spec:
  storageClassName: storage-{{ .Release.Name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.size }}

