#Provide the nodeName for node
#Eg. nodeName: bank1
nodeName: notarykd

#Provide the replica set for node deployed
#Eg. replicas: 1
replicas:

metadata:
  #Provide the namespace
  #Eg. namespace: default
  namespace:

#provide the pki image repo name, tag and specify pullpolicy
dockerImagePki:
  name: 
  tag:
  pullPolicy:

#initcontainer image specification
image:
  initContainerName:
  imagePullSecret:

#base directory ex. /opt/corda
volume:
  baseDir:

#vault related specifications
vault:
  address: 
  role:
  authpath:
  serviceaccountname:
  tokensecretprefix: 
  certsecretprefix: 
    
healthcheck:
  #Provide the interval in seconds you want to iterate till db to be ready
  #Eg. readinesscheckinterval: 5
  readinesscheckinterval: 10
  #Provide the threshold till you want to check if specified db up and running
  #Eg. readinessthreshold: 2
  readinessthreshold: 15

# signer service specifications
serviceSsh:
  type: ClusterIP
  port:
  targetPort:
  nodePort:
  
shell:
  user: signer
  password: signerP

#required parameter IP of idman and port
idmanPublicIP: 
idmanPort:

serviceLocations:
  identityManager:
    host: idman-internal
    port: 5052
  networkMap:
    host: nmap-internal
    port: 5050
  revocation:
    port: 5053

signers:
  CSR:
    schedule:
      interval: 1m
  CRL:
    schedule:
      interval: 1d
  NetworkMap:
    schedule:
      interval: 1m
  NetworkParameters:
    schedule:
      interval: 1m

cordaJarMx: 1

healthCheckNodePort: 0

# where is CENM service jar file stored
jarPath: bin

# where is CENM service configuration file stored
configPath: etc

# certificates subjects specification
pki:
  certificates:
    tlscrlsigner:
      subject: "CN=Test TLS Signer Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
      crl:
        issuer: "CN=Corda TLS Signer Certificate, OU=Corda, O=R3 HoldCo LLC, L=New York, C=US"
    cordarootca:
      subject: "CN=Test Root CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
    subordinateca:
      subject: "CN=Test Subordinate CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
    identitymanagerca:
      subject: "CN=Test Identity Manager Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
    networkmap:
      subject: "CN=Test Network Map Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
