api:
  - examples/**/*
aries-app:
  - examples/identity-app/**/*
besu:
  - platforms/hyperledger-besu/**/*
documentation:
  - docs/**/*
  - platforms/**/*.md
  - platforms/**/*.MD
corda:
  - platforms/r3-corda/**/*
Enterperise-Corda:
  - platforms/r3-corda-ent/**/*
fabric:
  - platforms/hyperledger-fabric/**/*
indy:
  - platforms/hyperledger-indy/**/*
quorum:
  - platforms/quorum/**/*  
shared:
  - platforms/shared/**/*
supplychain-app:
  - examples/supplychain-app/**/*
