# This role generates certificates for ambassador
# and places them in vault. Certificates are created using openssl
# This also creates the Kubernetes secrets
---
- name: Ensure ambassador tls dir exists
  include_role: 
    name: "../../shared/configuration/roles/check/setup"
  vars:
    check: "ensure_dir"
    path: "{{ ambassadortls }}"

# Check ambassador tls certs already created
- name: Check if ambassador tls already created
  shell: |
    vault kv get -format=yaml {{ component_name }}/tlscerts
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: ambassador_tls_certs
  ignore_errors: yes

# Gets the existing ambassador tls certs
- name: Get ambassador tls certs
  include_role: 
    name: "{{ playbook_dir }}/roles/setup/get_crypto"
  vars:
    vault_output: "{{ ambassador_tls_certs.stdout | from_yaml }}"
    type: "ambassador"
    cert_path: "{{ ambassadortls }}"
  when: ambassador_tls_certs.failed == False

# Generates the openssl file for domain
- name: Generate openssl conf file
  shell: |
    cd ./build
    cat <<EOF >openssl{{ component_name }}.conf
    [dn]
    CN={{ domain_name }}
    [req]
    distinguished_name = dn
    [EXT]
    subjectAltName=DNS:{{ domain_name }}
    keyUsage=digitalSignature
    extendedKeyUsage=serverAuth
    EOF
  vars:
    domain_name: "{{ component_name }}.{{ item.external_url_suffix }}"
  when: ambassador_tls_certs.failed == True

# Generates the ambassador tls certificates if already not generated
- name: Generate ambassador tls certs
  shell: |
    openssl req -x509 -out {{ ambassadortls }}/ambassador.crt -keyout {{ ambassadortls }}/ambassador.key -newkey rsa:2048 -nodes -sha256 -subj "/CN={{ domain_name }}" -extensions EXT -config "{{playbook_dir}}/build/openssl{{ component_name }}.conf" 
  vars:
    domain_name: "{{ component_name }}.{{ item.external_url_suffix }}"
  when: ambassador_tls_certs.failed == True

# Stores the genreated ambassador tls certificates to vault
- name: Putting tls certs to vault
  shell: |
    vault kv put {{ component_name }}/tlscerts tlscacerts="$(cat {{ ambassadortls }}/ambassador.crt | base64)" tlskey="$(cat {{ ambassadortls }}/ambassador.key | base64)"
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  when: ambassador_tls_certs.failed == True

# Check if Ambassador credentials exist already
- name: Check Ambassador cred exists
  k8s_facts:
    kind: Secret
    namespace: default
    name: "{{ component_name }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: get_ambassador_secret

# This task creates the Ambassador TLS credentials for ambassador
- name: Create the Ambassador credentials
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl create secret tls {{ component_name }}-ambassador-certs --cert={{ ambassadortls }}/ambassador.crt --key={{ ambassadortls }}/ambassador.key -n default
  when: get_ambassador_secret.resources|length == 0

# Copy generated crt to build location for doorman and networkmap
- name: Copy generated ambassador tls certs to given build location
  copy:
    src: "{{ ambassadortls }}/ambassador.crt"
    dest: "{{ cert_file }}"
    follow: yes
  when: cert_file is defined
