# Patch organizations namespaces
- name: Patching organizations namespaces
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item.name | lower }}-quo"
    state: present
    definition:
      metadata:
        finalizers: []
  register: patch_result
  loop: "{{ network['organizations'] }}"

# Delete organizations namespace 
- name: Delete organizations namespaces
  k8s:
    name: "{{ item.name | lower }}-quo"
    api_version: v1
    kind: Namespace
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
  vars:
    kubernetes: "{{ item.k8s }}"
  loop: "{{ network['organizations'] }}"
  when: patch_result is succeeded
