# Set enode_data_list to empty.
- name: Set enode_data_list to empty
  set_fact:
    enode_data_list: []

# Get enode data
- name: Get enode data for each node of the organization
  include_tasks: enode_data.yaml
  loop: "{{ network['organizations'] }}"
  loop_control:
    loop_var: org

# This task creates the Constellation Manager value file for each node of organization
- name: Create value file for constellation TM for each node in the organization
  include_role:
    name: helm_component
  vars:
    component_name: "{{ name }}{{ peer.name }}constellation"
    type: "constellation"
    genesis: "{{ lookup('file', '{{ build_path }}/genesis.json') | b64encode }}"
  loop: "{{ peers }}"
  loop_control: 
    loop_var: peer

- name: Git push
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ item.gitops.git_push_url }}"
    GIT_USERNAME: "{{ item.gitops.username }}"
    GIT_EMAIL: "{{ item.gitops.email }}"
    GIT_PASSWORD: "{{ item.gitops.password }}"
    GIT_BRANCH: "{{ item.gitops.branch }}"
    GIT_RESET_PATH: "platforms/quorum/configuration"
    msg: "Pushing Peer files"
