---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    privilege_escalate: true
    install_os: "linux"
    install_arch:  "amd64"
    bin_install_dir:  "~/bin"           
    kubeconfig_path: "/tmp/molecule/kind-default/kubeconfig"
    kubecontext: "kind"

  pre_tasks:
    - name: Create temp roles dir folder
      file:
        path: "{{ playbook_dir }}/../../shared/configuration"
        state: directory
    
    - name: Copy the roles
      copy:
        src: "{{ playbook_dir }}/../../../../shared/configuration/roles"
        dest: "{{ playbook_dir }}/../../shared/configuration"

  roles:
    - role: create/storageclass
      vars:
        org:
          name: test
          cloud_provider: aws
          k8s:
            config_file: "/tmp/molecule/kind-default/kubeconfig"
            context: kind
          gitops:
            release_dir: "test"
            git_repo: testurl
            username: testusername
            email: testemail
            password: testpassword
            branch: testbranch
        network:
          env:
            retry_count: 100
    - role: create/namespace_serviceaccount
      vars:
        org:
          name: test
          k8s:
            config_file: "/tmp/molecule/kind-default/kubeconfig"
            context: kind
          gitops:
            release_dir: "test"
            git_repo: testurl
            username: testusername
            email: testemail
            password: testpassword
            branch: testbranch
