##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if $.Values.labels }}
    {{- range $key, $value := $.Values.labels.service }}
    {{- range $k, $v := $value }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
  labels:
    run: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app: {{ .Release.Name }}
    app.kubernetes.io/component: fabric
    app.kubernetes.io/part-of: {{ include "fabric-orderernode.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ $.Values.service.serviceType }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    targetPort: 7050
    port: {{ $.Values.service.ports.grpc.clusterIpPort }}
    {{- if  (ne $.Values.service.serviceType "ClusterIP") }}
    nodePort: {{ $.Values.service.ports.grpc.nodeport }}
    {{- end }}
    name: grpc
  - name: grpc-web
    protocol: TCP
    targetPort: 7443
    port: 7443
  - name: operations
    protocol: TCP
    targetPort: 9443
    port: {{ $.Values.service.ports.metrics.clusterIpPort }}
  {{- if (eq $.Values.service.serviceType "ClusterIP") }}
  clusterIP: None
  {{- end }}
  
{{ if eq $.Values.global.proxy.provider "haproxy" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"  
spec:
  rules:
  - host: {{ .Release.Name }}.{{ $.Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ $.Values.service.ports.grpc.clusterIpPort }}
  - host: {{ .Release.Name }}-proxy.{{ $.Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 7443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ops
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"    
spec:
  rules:  
  - host: {{ .Release.Name }}-ops.{{ $.Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 10443
{{ end }}
