#############################################################################################
# This role deletes the helm releases and uninstalls Flux
#############################################################################################

#############################################################################################
- name: Deletes all the helmreleases CRD
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl delete --all helmrelease -n "{{ component_name }}"
  ignore_errors: yes

- name: Remove all Helm releases
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} helm ls --all --short | grep "{{ org_name }}" | xargs -L1 helm delete --purge
  ignore_errors: yes

- name: Deletes namespaces
  k8s:
    kind: Namespace
    name: "{{ component_name }}"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes
