##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# Delete flux ClusterRole resources
- name: Delete flux ClusterRole resources
  k8s:
    state: absent
    api_version: v1
    kind: ClusterRole
    namespace: flux-{{ network.env.type }}
    name: "{{ item[0] }}"
    kubeconfig: "{{ kubernetes.config_file }}"
  vars:
    kubernetes: "{{ item[1].k8s }}"
  with_nested:
      - ["crd-controller-flux-{{ network.env.type }}"]
      - "{{ network['organizations'] }}"
