# Set Variable channel_name_value
- name: Set Variable channel_name_value1 
  include_tasks: valuefile.yaml
  loop: "{{ channel.orderers }}"
  loop_control:
    loop_var: ord_org
  when: 
    - ord_org == org.name and ('2.2.' in network.version or '1.4.' in network.version)

# Set Variable channel_name_value
- name: Set Variable channel_name_value2
  include_tasks: valuefile.yaml
  when: channel.osn_creator_org.name == org.name and '2.5.' in network.version
