---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: myingress-default-backend
  name: myingress-default-backend
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    run: myingress-default-backend
  ports:
    - port: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: myhaproxy-ingress
  name: myhaproxy-ingress
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    run: myhaproxy-ingress
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.ports.http }}
    protocol: TCP
    targetPort: 80
  - name: https
    port: {{ .Values.service.ports.https }}
    protocol: TCP
    targetPort: 443
  - name: httpsback
    port: 443
    protocol: TCP
    targetPort: 443
  - name: stat
    port: 1936
    protocol: TCP
    targetPort: 1936