---
# Task to check if Job deployed and completed
# This task will try for a maximum of retry_count times with an interval of
# 60 seconds between each try
- name: 'Wait for {{ component_type }} {{ component_name }}'
  k8s_facts:
    kind: "Pod"
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    label_selectors:
      - job-name = {{ component_name }}
    field_selectors:
      - status.phase=Succeeded
  register: component_data
  retries: "{{ network.env.retry_count}}"
  delay: 60
  until: component_data.resources|length > 0
  when: component_type == "Job"


# Task to check if Pod is deployed and running
# This task will try for a maximum of 10 times with an interval of
# 60 seconds between each try
- name: 'Wait for {{ component_type }} {{ component_name }}'
  k8s_facts:
    kind: "Pod"
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    label_selectors:
      - app = {{ component_name }}
    field_selectors:
      - status.phase=Running
  register: component_data
  retries: "{{ network.env.retry_count}}"
  delay: 60
  until: component_data.resources|length > 0
  when: component_type == "Pod"
