# This playbook is a subsequent playbook
# This playbook does following
# 1. Installs chaincode provided in network.yaml from each peer
# 2. Instantiates chaincode from the creator participant peer of the channel( For Fabric 1.4)
# 3. Approves chaincode for Org and Commits chaincode on the peer (Fabric 2.X)
##########################################################################################
# DO NOT RUN THIS IF YOU HAVE NOT RUN deploy-network.yaml and deployed the Fabric network
##########################################################################################
# This playbook can only be run after all pods and orderers are available, and channel is created
# Please use the same network.yaml to run this playbook as used for deploy-network.yaml
---
- hosts: ansible_provisioners
  gather_facts: no
  tasks:

    - include_role:
        name: "create/chaincode/install"
      vars:
        docker_url: "{{ network.docker.url }}"
      loop: "{{ network['organizations'] }}"
      when: item.type == 'peer' and item.org_status == 'new'

    - include_role:
        name: "create/chaincode/instantiate"
      vars:
        participants: "{{ item.participants }}"
        docker_url: "{{ network.docker.url }}"
      loop: "{{ network['channels'] }}"
      when: add_new_org == 'false' and '1.4' in network.version

    - include_role:
        name: "create/chaincode/approve"
      vars:
        participants: "{{ item.participants }}"
        docker_url: "{{ network.docker.url }}"
      loop: "{{ network['channels'] }}"
      when: participants is defined and '2.' in network.version

    - include_role:
        name: "create/chaincode/commit"
      vars:
        participants: "{{ item.participants }}"
        docker_url: "{{ network.docker.url }}"
        approvers: "{{ item.endorsers }}"
      loop: "{{ network['channels'] }}"
      when: add_new_org == 'false' and '2.' in network.version    
        
    # This task invokes chaincode after the chaincode installation for the new organization to 
    # be added in existing network
    - include_role:
        name: "create/chaincode/invoke"
      vars:
        participants: "{{ item.participants }}"
        docker_url: "{{ network.docker.url }}"
      loop: "{{ network['channels'] }}"
      when: add_new_org == 'true'

    # delete build directory
    - name: Remove build directory
      file:
        path: "./build"
        state: absent
    
  vars: #These variables can be overriden from the command line
    privilege_escalate: false           #Default to NOT escalate to root privledges
    install_os: "linux"                 #Default to linux OS
    install_arch:  "amd64"              #Default to amd64 architecture
    bin_install_dir:  "~/bin"           #Default to /bin install directory for binaries
    add_new_org: 'false'
