apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ca
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: minikube
        cloudNativeServices: false
        kubernetesUrl: https://127.0.0.1:32776
      vault:
        type: hashicorp
        network: fabric
        address: http://172.27.31.179:8200
        authPath: devwarehouse
        secretEngine: secretsv2
        secretPrefix: "data/devwarehouse"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: org5proxy.blockchaincloudpoc.com

    storage:
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: warehouse-admin
      adminPassword: warehouse-adminpw
      subject: "/C=US/ST=Massachusetts/L=Boston/O=Warehouse"
      clusterIpPort: 7054

    labels:
      service:
        - example1: example2
      pvc:
      deployment:
