# Patching GitRepository resources
- name: Patching GitRepository resources
  k8s:
    api_version: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    namespace: flux-{{ network.env.type }}
    name: flux-{{ network.env.type }}
    state: present
    definition:
      metadata:
        finalizers: []
  register: patch_result
  loop: "{{ network['organizations'] }}"
  
# Deleting the same patched GitRepository resources
- name: Delete GitRepository resource
  k8s:
    api_version: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    namespace: flux-{{ network.env.type }}
    name: flux-{{ network.env.type }}
    state: absent
  loop: "{{ network['organizations'] }}"
  when: patch_result is succeeded
