##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-config
    app.kubernetes.io/component: fabric
    app.kubernetes.io/part-of: {{ include "fabric-peernode.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  CORE_PEER_ID: {{ .Release.Name }}.{{ .Release.Namespace }}
  FABRIC_LOGGING_SPEC: "grpc=debug:{{ $.Values.peer.logLevel }}"
  CORE_LEDGER_STATE_STATEDATABASE: CouchDB
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: localhost:5984
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: "{{ $.Values.peer.couchdb.username }}"
  CORE_PEER_ADDRESS: {{ .Release.Name }}.{{ .Release.Namespace }}:{{ $.Values.service.ports.grpc.clusterIpPort }}
  CORE_PEER_GOSSIP_BOOTSTRAP: {{ .Release.Name }}.{{ $.Values.peer.gossipPeerAddress }}
  {{ if $.Values.peer.gossipExternalEndpoint }}
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: {{ .Release.Name }}.{{ $.Values.peer.gossipExternalEndpoint }}
  {{ end }}
  CORE_PEER_LOCALMSPID: {{ $.Values.cli.peer.localMspId }}
  CORE_PEER_TLS_ENABLED: "{{ $.Values.cli.peer.tlsStatus }}"
  CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/crypto/tls/server.crt
  CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/crypto/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/crypto/msp/tlscacerts/tlsca.crt
  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_PEER_GOSSIP_ORGLEADER: "false"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_NETWORKID: {{ .Release.Name }}.{{ .Release.Namespace }}
  CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/fabric/crypto/msp
  GODEBUG: "netdns=go"
  CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"
  CORE_CHAINCODE_BUILDER: "{{ $.Values.peer.builder }}:{{ $.Values.global.network.version }}"
  CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-msp-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-msp-config
    app.kubernetes.io/component: fabric
    app.kubernetes.io/part-of: {{ include "fabric-peernode.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  mspConfig: |
    {{if  ($.Values.peer.mspConfig.organizationalUnitIdentifiers) }}
      OrganizationalUnitIdentifiers:{{ range $.Values.peer.mspConfig.organizationalUnitIdentifiers }}
        - Certificate: cacerts/ca.crt
          OrganizationalUnitIdentifier: {{ . }}{{ end }}{{end}}
      NodeOUs:
        Enable: true
        ClientOUIdentifier:
          Certificate: cacerts/ca.crt
          OrganizationalUnitIdentifier: {{ $.Values.peer.mspConfig.nodeOUs.clientOUIdentifier.organizationalUnitIdentifier }}
        PeerOUIdentifier:
          Certificate: cacerts/ca.crt
          OrganizationalUnitIdentifier: {{ $.Values.peer.mspConfig.nodeOUs.peerOUIdentifier.organizationalUnitIdentifier }}
        AdminOUIdentifier:
          Certificate: cacerts/ca.crt
          OrganizationalUnitIdentifier: {{ $.Values.peer.mspConfig.nodeOUs.adminOUIdentifier.organizationalUnitIdentifier }}
        OrdererOUIdentifier:
          Certificate: cacerts/ca.crt
          OrganizationalUnitIdentifier: {{ $.Values.peer.mspConfig.nodeOUs.ordererOUIdentifier.organizationalUnitIdentifier }}

---
{{- $file := .Files.Get "files/core.yaml" }}
{{ if $file }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-builders-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: builders-config
    app.kubernetes.io/component: fabric
    app.kubernetes.io/part-of: {{ include "fabric-peernode.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  core.yaml: {{ .Files.Get "files/core.yaml" | nindent 8 | quote }}
{{ end }}