##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if or $.Values.global.proxy (and $.Values.service.loadBalancerType (eq $.Values.service.loadBalancerType "Internal")) }}
  annotations:
    {{- include "labels.pvc" . | nindent 2 }}
  {{- if and $.Values.service.loadBalancerType (eq $.Values.service.loadBalancerType "Internal") }}
    cloud.google.com/load-balancer-type: "Internal"
  {{- end }}
  {{- end }}
  labels:
    run: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: fabric
    app.kubernetes.io/part-of: {{ include "fabric-peernode.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- include "labels.pvc" . | nindent 2 }}
spec:
  type: {{ $.Values.service.serviceType }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: grpc
    protocol: TCP
    targetPort: 7051
    port: {{ $.Values.service.ports.grpc.clusterIpPort }}
    {{- if $.Values.service.ports.grpc.nodePort }}
    nodePort: {{ $.Values.service.ports.grpc.nodePort }}
    {{- end }}
  - name: events
    protocol: TCP
    targetPort: 7053
    port: {{ $.Values.service.ports.events.clusterIpPort }}
    {{- if $.Values.service.ports.events.nodePort }}
    nodePort: {{ $.Values.service.ports.events.nodePort }}
    {{- end }}
  - protocol: TCP
    name: couchdb
    targetPort: 5984
    port: {{ $.Values.service.ports.couchdb.clusterIpPort }}
    {{- if $.Values.service.ports.couchdb.nodePort }}
    nodePort: {{ $.Values.service.ports.couchdb.nodePort }}
    {{- end }}
  - name: grpc-web
    protocol: TCP
    targetPort: 7443
    port: 7443
  - name: operations
    protocol: TCP
    targetPort: 9443
    port: {{ $.Values.service.ports.metrics.clusterIpPort }}
  {{- if (eq $.Values.service.serviceType "ClusterIP") }}
  clusterIP: None
  {{- end }}
  {{- if $.Values.service.loadBalancerIP }}
  loadBalancerIP: {{ $.Values.service.loadBalancerIP }}
  {{- end }}

{{- if eq $.Values.global.proxy.provider "haproxy" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace:  {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"  
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Release.Namespace }}.{{ $.Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ $.Values.service.ports.grpc.clusterIpPort }}
  - host: {{ .Release.Name }}-proxy.{{ .Release.Namespace }}.{{ $.Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 7443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ops
  namespace:  {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: {{ .Release.Name }}-ops.{{ .Release.Namespace }}.{{ $.Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 9443
{{- end }}
