##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# Get all helm charts resources in the namespace
- name: Get all Helm Charts
  k8s_info:
    api_version: source.toolkit.fluxcd.io/v1beta2
    kind: HelmChart
    namespace: flux-{{ network.env.type }}
  register: helm_charts

# Patch all helm charts resources in the namespace
- name: Patching all Helm Charts resources
  k8s:
    api_version: source.toolkit.fluxcd.io/v1beta2
    kind: HelmChart
    namespace: flux-{{ network.env.type }}
    name: "{{ item.metadata.name }}"
    state: present
    definition:
      metadata:
        finalizers: []
  loop: "{{ helm_charts.resources }}"
  register: patch_result
  
# Delete all Helm Charts resources in the namespace
- name: Delete all Helm charts resources
  k8s:
    api_version: source.toolkit.fluxcd.io/v1beta2
    kind: HelmChart
    namespace: flux-{{ network.env.type }}
    name: "{{ item.metadata.name }}"
    state: absent
  loop: "{{ helm_charts.resources }}"
  when: patch_result is succeeded
