##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "labels.deployment" . | nindent 2 }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name:  osn-createchannel-{{ .Release.Name }}
    app.kubernetes.io/component: fabric-osnadmin-channel-create-job
    app.kubernetes.io/part-of: {{ include "fabric-osnadmin-channel-create.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
    {{ include "labels.deployment" . | nindent 6 }} 
data:
  CHANNEL_NAME: {{ .Release.Name }}
  ADMIN_TLS_CERTS: /opt/gopath/src/github.com/hyperledger/fabric/crypto
  GENESIS_FILE: /opt/gopath/src/github.com/hyperledger/fabric/orderer/genesis
{{- if $.Values.addOrderer }}
  CORE_PEER_LOCALMSPID: {{ $.Values.orderer.localmspid }}
  CORE_PEER_TLS_ROOTCERT_FILE: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/tlscacerts/tlsca.crt
  CORE_PEER_MSPCONFIGPATH: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp
  CORE_PEER_ADDRESS: {{ $.Values.orderer.address }}
  ORDERER_CA: /opt/gopath/src/github.com/hyperledger/fabric/crypto/{{ $.Values.orderer.name }}/tls/ca.crt
{{ end }}

