##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openssl-config-file
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: fabric-cacerts-gen-job
    app.kubernetes.io/component: fabric-cacerts-gen-job
    app.kubernetes.io/part-of: {{ include "fabric-cacerts-gen.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
data:
   openssl.conf: |-
    [req]
    req_extensions = v3_req
    distinguished_name = dn

    [dn]

    [v3_req]
    basicConstraints = critical, CA:TRUE
    keyUsage = critical,digitalSignature, keyEncipherment, keyCertSign, cRLSign
    subjectKeyIdentifier = hash
 
