---
# Task to check if Namespace, Clusterrolebinding or StorageClass is created
# This task will try for a maximum of 10 times with an interval of
# 35 seconds between each try
- name: Wait for {{ component_type }} {{ component_name }}
  k8s_facts:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: component_data
  retries: "{{ network.env.retry_count}}"
  delay: 35
  until: component_data.resources|length > 0
  when: component_type == "Namespace" or component_type == "ClusterRoleBinding" or component_type == "StorageClass"


# Task to check if ServiceAccount is created
# This task will try for a maximum of 10 times with an interval of
# 35 seconds between each try
- name: Wait for {{ component_type }} {{ component_name }}
  k8s_facts:
    kind: "{{ component_type }}"
    name: "{{ component_name }}"
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: component_data
  retries: "{{ network.env.retry_count}}"
  delay: 35
  until: component_data.resources|length > 0
  when: component_type == "ServiceAccount"
