#helm install ca-certs -f values/noproxy-and-novault/ordererOrganization/genesis.yaml -n supplychain-net fabric-genesis
global:
  serviceAccountName: vault-auth
  vault:
    type: kubernetes
  cluster:
    provider: azure
    cloudNativeServices: false
  proxy:
    provider: none
    externalUrlSuffix: supplychain-net
  network:
    version: 2.5.4

consensus:
  name: raft

organizations:
  - organization:
    name: supplychain 
    type: orderer    
    orderers:
    - orderer:
      name: orderer1
      ordererAddress: orderer1.supplychain-net:7050
    - orderer:
      name: orderer2
      ordererAddress: orderer2.supplychain-net:7050
    - orderer:
      name: orderer3
      ordererAddress: orderer3.supplychain-net:7050  

  - organization:
    name: carrier
    type: peer  
    peers:
    - peer:
      name: peer0-carrier          
      peerAddress: peer0-carrier.carrier-net:7051 # External URI of the peer

channels:
  - channel:
    channelName: allchannel
    consortium: SupplyChainConsortium
    orderers:
      - supplychain  
    participants:
    - organization:
      name: carrier
    genesis:
      name: OrdererGenesis

settings:
  removeGenesisOnDelete: true
  removeConfigMapOnDelete: true
