global:
  serviceAccountName: vault-auth
  vault:
    type: kubernetes

  cluster:
    provider: azure
    cloudNativeServices: false
  
  proxy:
    provider: none
    externalUrlSuffix: supplychain-net

network:
  version: 2.5.4

orderer:
  logLevel: info
  localMspId: supplychainMSP
  tlsstatus: true

consensus:
  name: raft
