k8_templates:
  namespace: namespace_component.tpl
  vault-reviewer: reviewer.tpl
  vaultAuth: vault_auth.tpl
  reviewer_rbac: reviewer_rbac.tpl
  ca-tools-deployment: ca_tools_deploy.tpl
  ca-tools-volume: ca_tools_vol.tpl
  existing_peer_cli_job: existing_peer_cli.tpl
 