# Default values for Crypto IBFT chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#############################################################
#                   Basic Configuration                     #
#############################################################

peer:
  # Provide the name of the peer
  # Eg. name: carrier
  name:
  # Provide the passphrase for building the crypto files
  # Eg. 12345
  gethPassphrase:
# This section contains the Quorum Crypto IBFT metadata.
metadata:
  # Provide the namespace for Quorum.
  # Eg. namespace: cenm
  namespace:
  # Provide any additional labels for Quorum Crypto IBFT.

# Provide information regarding the Docker images used.
image:
  # Provide the alpine utils image, which is used for all init-containers of deployments/jobs.
  # NOTE: The alpine image used is the base alpine image with CURL installed.
  # Eg. initContainerName: hyperledgerlabs/alpine-utils:1.0
  initContainerName:
  # Pull policy to be used for the Docker image
  # Eg. pullPolicy: Always
  pullPolicy:
  # Pull quorum Docker image
  node: 

#############################################################
#               HashiCorp Vault Configuration               #
#############################################################
# NOTE: Make sure that the vault is already unsealed, intialized and configured to 
# use Kubernetes service account token based authentication. 
# For more info, see https://www.vaultproject.io/docs/auth/kubernetes

vault:
  # Provide the vault address
  # Eg. address: http://vault.example.com:8200
  address: 
  # Provide the vault role used.
  # Eg. role: vault-role
  role:
  # Provide the authpath configured to be used.
  authPath:
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceAccountName:
  # Provide the vault path where the certificates are stored
  # Eg. certsecretprefix: secret/cenm-org-name
  certSecretPrefix:
