apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Values.metadata.name }}"
  namespace: "{{ $.Values.metadata.namespace }}"
spec:
  type: NodePort
  ports:
  - name: indy-alice-service
    port: {{ $.Values.service.ports.service }}
    targetPort: {{ $.Values.service.ports.service }}
    nodePort: {{ $.Values.service.ports.service }}
  - name: indy-alice-endpoint
    port: {{ $.Values.service.ports.endpoint }}
    targetPort: {{ $.Values.service.ports.endpoint }}
    nodePort: {{ $.Values.service.ports.endpoint }}
  - name: indy-alice-webhook
    port: {{ $.Values.service.ports.webhook }}
    targetPort: {{ $.Values.service.ports.webhook }}
    nodePort: {{ $.Values.service.ports.webhook }}
  selector:
    app: "{{ $.Values.metadata.name }}"
