#helm install supplychain-ca -f values/proxy-and-vault/ordererOrganization/ca-server.yaml -n supplychain-net fabric-ca-server
global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    imageSecretName: regcred
    tls: false

  cluster:
    provider: azure
    cloudNativeServices: false
    kubernetesUrl: https://kubernetes.url
    
  proxy:
    provider: haproxy
    externalUrlSuffix: test.yourdomain.com

cacerts:
  ca:
    orgName: supplychain
    subject: /C=GB/ST=London/L=London/O=Orderer

catools:
  orgData:
    orgName: supplychain
    type: orderer
    componentSubject: O=Orderer,L=51.50/-0.13/London,C=GB
    certSubject: O=Orderer/L=51.50,-0.13,London/C=GB
    componentCountry: UK
    componentState: London
    componentLocation: London

  orderers:
    - orderer1
    - orderer2
    - orderer3

server:
  tlsStatus: true
  admin: supplychain-admin

settings:
  removeOrdererTlsOnDelete: true
  removeCertsOnDelete: true
