#helm install orderer1 -f values/proxy-and-vault/ordererOrganization/orderer.yaml -n supplychain-net fabric-orderernode
global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    imageSecretName: regcred

  cluster:
    provider: azure
    cloudNativeServices: false

  proxy:
    provider: haproxy
    externalUrlSuffix: test.yourdomain.com

network:
  version: 2.5.4

orderer:
  logLevel: info
  localMspId: supplychainMSP
  tlsstatus: true
  ordererAddress: orderer1.test.yourdomain.com:443

consensus:
  name: raft
