global:
  #Provide the service account name which will be created.
  serviceAccountName: vault-auth  
  cluster:
    provider: azure  # choose from: minikube | aws | azure | gcp
    cloudNativeServices: false # only 'false' is implemented
  vault:
    type: hashicorp
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"

network:
  version: 2.5.4

orderers:
  - orderer1   
  - orderer2 
  - orderer3
