- name: "Waiting for orderer pod {{ orderer.name }} in {{ orderer_namespace }}"
  include_role:
    name: "../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ orderer_namespace }}"
    component_name: "{{ orderer.name }}"
    kubernetes: "{{ ordererorg.k8s }}"
    check: "app"
  loop: "{{ ordererorg.services.orderers }}"
  loop_control:
    loop_var: orderer
