kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.nodeName }}
  {{- if .Values.deployment.annotations }}
    annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
  {{- end }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: {{ .Values.nodeName }}
        app.kubernetes.io/name: {{ .Values.nodeName }}
        app.kubernetes.io/instance: {{ .Release.Name }} 
    spec:
      hostname: {{ .Values.nodeName }}
      imagePullSecrets:
        - name: {{ .Values.expressapp.pullSecrets | default "regcred" }}
      containers:     
      - name: expressapp
        image: {{ .Values.expressapp.image }}
        imagePullPolicy: {{ .Values.expressapp.pullPolicy }}
        env:
        - name: GANACHE_SERVER
          value: "{{ .Values.expressapp.env.ganache_server }}"
        - name: PRODUCT_CONTRACT_ADDRESS
          value: "{{ .Values.expressapp.env.product_contract_address }}"
        - name: NODE_IDENTITY
          value: "{{ .Values.expressapp.env.node_identity }}"
        - name: NODE_SUBJECT
          value: "{{ .Values.expressapp.env.node_subject }}"
        - name: NODE_ORGANIZATION
          value: "{{ .Values.expressapp.env.node_organization }}"
        - name: NODE_ORGANIZATION_UNIT
          value: "{{ .Values.expressapp.env.node_organization_unit }}"

        ports:
        - containerPort: {{ .Values.expressapp.nodePorts.targetPort }}
          name: expressapp

