
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride:
# This section contains the ipfs node config values
config:
  healthCheckPort: 80
  healthCheckPollPeriod: 30000
  healthCheckTimeout: 2000
  nodeHost:  # This overrides dscpNode.enabled
  nodePort:
  # publicKey:
  # privateKey:
  # Sets the log level - default trace, example values: all, debug, off, info, fatal
  logLevel:
  # Sets the ipfs api port - default
  ipfsApiPort:
  # Sets the ipfs swarm port - default 4001
  ipfsSwarmPort:
  # Remote location where ipfs will store data - default /ipfs
  ipfsDataPath:
  # Remote location in which the ipfs binary is stored - default /usr/local/bin/ipfs
  ipfsCommand:
  ipfsArgs:
  # ipfsBootNodeAddress: /dnsaddr/blah.test.com/p2p/PeerId # Valid Format for this is /multiaddr/PeerId see https://github.com/multiformats/multiaddr
  # Sets the ipfs log level - default trace, example values: debug, info, warn, error, dpanic, panic, fatal
  ipfsLogLevel:
  ipfsSwarmAddrFilters:

service:
  swarm:
    annotations: {}
    enabled: true
    port: 4001
  api:
    annotations: {}
    enabled: true
    port: 5001

statefulSet:
  annotations: {}
  livenessProbe:
    enabled: true

# This section contains the values relating to the ipfs image as of now the image is pulled from the digicatapult github container registry
image:
  # Image repository in which the ipfs node image will be pulled from - default pull from ghcr.io/inteli-poc/dscp-ipfs
  repository:
  # If the image is not present in the kubernetes docker daemon it will attempt to pull the image from the aforementioned repository - default IfNotPresent
  pullPolicy: IfNotPresent
  # Specifying the version of the image to pull - default 1.2.3
  tag:

initContainer:
  # Provide the alpine utils image, which is used for all init-containers of deployments/jobs.
  # NOTE: The alpine image used is the base alpine image with CURL installed.
  # Eg. image: hyperledgerlabs/alpine-utils:1.0
  image: ghcr.io/hyperledger/alpine-utils:1.0
  # Pull policy to be used for the Docker image
  # Eg. pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent

# This section contains the values relating to the ipfs storage and data volume size
storage:
  # Default for storage class is gcpstorageclass
  storageClass: ""
  # Sets the volume size for the above storageClass - default 1
  dataVolumeSize: 1  # in Gigabytes

# Determines whether this ipfs node is a vitalAM node or not
dscpNode:
  enabled: false

# Proxy section contains the proxy provider and ports
proxy:
  # Mention the proxy provider. Currently ambassador is supported
  # eg. provider: ambassador
  provider: ambassador
  # url that will be added in DNS recordset
  # eg. external_url: test.substrate.example.com
  external_url:
  # Mention the swarm port configured on proxy.
  # NOTE: Make sure that the port is enabled and not binded on the proxy.
  # Eg. port: 15010
  port:
  # Provide the secret name which contains the certificate
  certSecret: 
 
vault:
  # Provide the vault address
  # Eg. address: http://vault.example.com:8200
  address: 
  # Provide the vault role used.
  # Eg. role: vault-role
  role:
  # Provide the authpath configured to be used.
  authpath:
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceAccountName:
  # Provide the vault path where the certificates are stored
  # Eg. certsecretprefix: secret/cenm-org-name
  certSecretPrefix:
